### ISSUE TITLE
Keyboard not being invoked in android

### ISSUE THREAD

**Issue by preveenraj** [bony2023/react-terminal#1]
While using the terminal in android chrome, the terminal on focus is not bringing the keyboard into the view.
Only with the soft keyboard, a user can type in commands when using the terminal in smart phones

**Comment by defCoding** [comment]
It looks like with the latest version, this issue has resurfaced. Tested on Android with Brave, DuckDuckGo, and Firefox browser -- keyboard does not come into view.

**Comment by Q0** [comment]
> It looks like with the latest version, this issue has resurfaced. Tested on Android with Brave, DuckDuckGo, and Firefox browser -- keyboard does not come into view.

Checked all browsers. The keyboard doesn't pop up at all.

@bony2023 @0NotApplicable0 can you fix it please? in features states support for mobile devices, but in fact it does not work

**Comment by 0NotApplicable0** [comment]
Hi @Q0, check out my response on #283
