### ISSUE TITLE
ability to add any command

### ISSUE THREAD

**Issue by jseparovic** [bony2023/react-terminal#140]
I'd like to be able to run a callback on any string that is input and not have specific commands.

Something like this:
```
<ReactTerminal
    commands={{
        '*': handleCommand
    }}
/>
```

My commands are sent to a server which does the validation so I don't know them upfront.

**Comment by bony2023** [comment]
@jseparovic Thanks, that's a great idea. The component provides the ability to pass a custom function in the `errorMessage` prop so any unrecognized command will call that handler. However, to make things more clear, I have added a `defaultHandler` prop in the latest version ([v1.2.8](https://www.npmjs.com/package/react-terminal/v/1.2.8)) which if passed will be called when the command is not found:

```javascript
async function handleAllCommands(command, commandArguments) {
  // await ... pass the command and arguments to server
}

<ReactTerminal
    defaultHandler={handleAllCommands}
/>
```

**Comment by bony2023** [comment]
Closing the issue as the fix has been released ([commit](https://github.com/bony2023/react-terminal/commit/b022db076a0facf813948bd86ab80c9da31da5bc)).
