### ISSUE TITLE
How to pass JSX/HTML as command value

### ISSUE THREAD

**Issue by abhijhacodes** [bony2023/react-terminal#155]
The documentation says 
`List of commands to be provided as a key value pair where value can be either a string, JSX/HTML tag or callback`
But how to pass this value ?
I'm doing this

```jsx
 const commands = {
    whoami: "Abhishek Jha",
    about:
      "<h1>I'm Abhishek Jha.</h1> <br/> Competitive programmer & Full stack developer.",
    cd: (directory) => `changed path to ${directory}`,
  };
```

Am I doing any mistake in syntax or this doesn't work ?

**Comment by defCoding** [comment]
Try doing something like this:
```js
about:
    (<><h1>I'm Abhishek Jha.</h1> <br/> Competitive programmer & Full stack developer.</>)
```

**Comment by abhijhacodes** [comment]
Thanks @defCoding , it works :D
