### ISSUE TITLE
Firefox copy paste TypeError: navigator.clipboard.readText is not a function

### ISSUE THREAD

**Issue by asnewman** [bony2023/react-terminal#219]
When attempting to paste using Firefox the error `TypeError: navigator.clipboard.readText is not a function` appears and the paste does not succeed. Based on https://stackoverflow.com/questions/67440036/navigator-clipboard-readtext-is-not-working-in-firefox it looks like Firefox requires a different API call for pasting (compared to Chrome).

**Comment by bony2023** [comment]
It looks like Firefox only supports reading from clipboard through browser extensions and not web app. 

https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText

**Comment by hermanwhyd** [comment]
@bony2023 could you pls share how to resolve this issue? i'm using latest version got same experience, only on FF.

**Comment by bony2023** [comment]
@hermanwhyd As mentioned in my above reply `readText` API is [unsupported on Firefox](https://caniuse.com/?search=clipboard.read). Unfortunately the package is dependent on that API to make copy/paste work.
