### ISSUE TITLE
Keyboard not being invoked in android

### ISSUE THREAD

**Issue by Q0** [bony2023/react-terminal#283]
The keyboard does not pop up on mobile devices when you click on the terminal.

Checked on Android 10 and 13.
Browsers: chrome, firefox
Version package: 1.3.0

Tested page: react-terminal.surge.sh

**Comment by 0NotApplicable0** [comment]
Hi @Q0 this was fixed, the version on NPM has not been updated just yet it looks like. 
If you need the updates before a new release what you could do is clone the repository, pack it, and then put it in your project.

**Comment by bony2023** [comment]
@Q0 The latest version 1.3.1 fixes the mobile issue. Please update the library to the same
