### ISSUE TITLE
remove top bar?

### ISSUE THREAD

**Issue by Trithir** [bony2023/react-terminal#29]
Is there a way to remove the top bar with the red/yellow/green buttons? The look clashes with my project, and the buttons don't seem to work.

**Comment by bony2023** [comment]
You can pass the `showControlButtons` as `false` and it will remove the 3 buttons but will still show the bar. I'll see if I can integrate this feature in my next release.

**Comment by bony2023** [comment]
PR merged to develop. Will be available in the next version.
