### ISSUE TITLE
Upgrade react peer dependency to 17 or later from current 16 version

### ISSUE THREAD

**Issue by preveenraj** [bony2023/react-terminal#30]

**Comment by preveenraj** [comment]
I am using react version 17.0.1 in my nextjs site, and I wanted to try the terminal in it. Unfortunately, it threw errors regarding the peer dependency of react-terminal is react 16. 
Any way to workaround this? or will it be feasible for you to upgrade this to 17?
@bony2023

**Comment by bony2023** [comment]
I think it should be easy enough to upgrade this package to use React 17+. Will open up a PR soon for this. Thanks for letting me know

**Comment by benmneb** [comment]
I second this! Looks great.

**Comment by benmneb** [comment]
I'm willing to help with this. I don't really know what to do but if someone can tell me I can probably do it.

**Comment by bony2023** [comment]
Thanks, @benmneb. I was able to look into it this weekend and updated the project's peer dependency to React 17.0.2. This will be released in the next version.
