### ISSUE TITLE
Multiline output

### ISSUE THREAD

**Issue by benmneb** [bony2023/react-terminal#31]
In the README picture you have a detailed multiline output, how is this accomplished?

**Comment by seeward** [comment]
Came here for the same question - I can't get my output to include whitespace or line breaks - any advice?

**Comment by bony2023** [comment]
Hi there, you can use HTML's `<br/>` tag to achieve this. Please check the below code from my website:
https://github.com/bony2023/bonyroopchandani.com/blob/33e85560f4ed5a7c2c0970791c2df410e42d0f06/src/components/AboutConsole.js#L14-L18

**Comment by benmneb** [comment]
do you think this should be added to the `README`?

**Comment by bony2023** [comment]
Makes sense. Added to readme as the description of the prop.
