### ISSUE TITLE
`welcomeMessage` not adding line break

### ISSUE THREAD

**Issue by benmneb** [bony2023/react-terminal#32]
The `welcomeMessage` is output on the same line as what should be the preceeding line.

<img width="201" alt="Screen Shot 2021-08-07 at 11 12 06 pm" src="https://user-images.githubusercontent.com/62878664/128604875-be9ec45f-d5a6-41d6-b2f0-55ef7b0cf510.png">

See: https://x42pi.csb.app/

**Comment by bony2023** [comment]
I have answered how to achieve this here: https://github.com/bony2023/react-terminal/issues/31
The reason this is not included by default is sometimes the author might want to start the prompt from the same line as the welcome message.

**Comment by benmneb** [comment]
awesome. thanks
