### ISSUE TITLE
Multiple arguments in command functions

### ISSUE THREAD

**Issue by benmneb** [bony2023/react-terminal#34]
Is it possible to somehow have multiple function arguments in commands? ie.

```
const commands = {
  email: (message, address) => `"${message}" sent to "${address}"` 
}
``` 

The current behaviour of running `email message address` just includes the value of both arguments in the first argument, leaving the second undefined. Is there a way to seperate them?

**Comment by bony2023** [comment]
The callback function can decide to split the argument into however it likes, but I think it's a good idea to have multiple arguments to simulate a real terminal. I'll look to implement this feature. Thanks

**Comment by bony2023** [comment]
@itsezc I found it's tricky to split arguments to implement this feature. For instance:

```bash
> email send_this_message example@example.com
```
is fine to parse, but
```bash
> email send this message example@example.com
```
contains 4 arguments and the library cannot decide how to send these to the callback function. Though I am open to ideas on how this can be implemented better, I closed the issue for now.

**Comment by raaaahman** [comment]
You may implement a unix like options syntax:

```
> email --message="send this message" --to=example@example.com
```

or 

```
> email -m "send this message" example@example.com
```

With an API close to (for last example):

```
const commands = {
  email: (options, ...args) => `"${options.m}" sent to "${args[0]}"` 
}
```
