### ISSUE TITLE
Empty spaces are getting automatically removed

### ISSUE THREAD

**Issue by dennisfleischmann** [bony2023/react-terminal#385]
Reproduction step

Setup example Component

enter
cd aaaaa       bbbbbbb

expected output:
cd aaaaa       bbbbbbb
actual output:
cd aaaaa bbbbbbb

**Comment by dennisfleischmann** [comment]
I fixed it

Solution:

   
            return (
                <>
                <pre>{result.warnings}</pre>
                <pre>{result.output}</pre>
             </>

**Comment by bony2023** [comment]
Closing as the fix is to just format the output correctly as described above.
