### ISSUE TITLE
Prop to remove the cursor(caret)

### ISSUE THREAD

**Issue by sorkinl** [bony2023/react-terminal#6]
Hi! Your component works great! I am trying to combine it with an auto typing animation. What could be very handy is a prop to disable handleKeyDown functionality entirely or with delay, as well as removing the blinking cursor. I am looking for an open-source project to work on and I would love to take the above issues on as a challenge if you let me!

**Comment by broopchandani-hiver** [comment]
Hi @sorkinl,

Thanks for the suggestion. You can go ahead and extend the terminal accordingly to add the functionality. Waiting to see your PR. 

Best,
Bony

**Comment by bony2023** [comment]
Hi @sorkinl,

Thanks for the suggestion. You can go ahead and extend the terminal accordingly to add the functionality. Waiting to see your PR.

Best,
Bony

**Comment by sorkinl** [comment]
@bony2023 
I made a PR and added two props. I am not sure if I should close this issue now.

**Comment by bony2023** [comment]
@sorkinl Thank you for your contribution. A new version has been released for this feature.
