### ISSUE TITLE
Programatically run commands

### ISSUE THREAD

**Issue by benmneb** [bony2023/react-terminal#63]
Is it possible to run commands or just print things to the terminal without actually typing in a command? At the moment the following code runs (console.log works), but just doesnt print anything in the terminal. Seems unusual.

Example:
```
const welcomeMessage = (
    <span>
        <span style={link} onClick={() => commands.copy()}>
          Click here
        </span>{" "}
        to try to run a function to print to terminal.
      </span>
  );

const commands = {
    copy: () => {
      console.log("success?");
      return <span>Success!</span>;
    }
  };
```

[EDIT ON CODESANDBOX](https://codesandbox.io/s/react-terminal-programatically-run-commands-tnifd?file=/src/App.js)

**Comment by bitcoinbrisbane** [comment]
Seems realsted to https://github.com/bony2023/react-terminal/issues/173

**Comment by bony2023** [comment]
feature added in https://github.com/bony2023/react-terminal/pull/233
