### ISSUE TITLE
support copy/paste

### ISSUE THREAD

**Issue by danfernand** [bony2023/react-terminal#92]
good afternoon, love the terminal! Great job. 

Found a quick lil bug with copy/paste. Looked at the code and cannot find it implemented.

Let me know if this is a use-case that is being worked on or point me to the place where I can implemented and ill submit a pr, thanks!

**Comment by danfernand** [comment]
looks like here is the issue

https://github.com/bony2023/react-terminal/blob/a6aee4125f1c51fe6be6e9625ae76107eb9da7a2/src/hooks/editor.tsx#L40

**Comment by VicAv99** [comment]
This would be very useful

**Comment by bony2023** [comment]
Copy/paste has been on my todo for quite some time. Finally the latest version ([1.2.5](https://www.npmjs.com/package/react-terminal/v/1.2.5)) now supports copy and pasting on the terminal. Thanks for raising this issue and contributing to the package. I will close this now.
